### ISSUE TITLE
0 no patterns matched tag="winevt.raw"

### ISSUE THREAD

**Issue by mimachniak** [fluent/fluent-plugin-windows-eventlog#12]
Hello,
I get warrning and cannot go forward with this issue.

**Comment by cosmo0920** [comment]
Could you show us your Fluentd configuration?

**Comment by repeatedly** [comment]
This is FAQ.
Check document first: https://docs.fluentd.org/v1.0/articles/faq#i-got-%E2%80%9Cno-patterns-matched%E2%80%9D-in-the-log,-why?

**Comment by cosmo0920** [comment]
I'd answered in https://github.com/fluent/fluentd-docs/issues/572#issuecomment-428057221.
Closing.
