### ISSUE TITLE
Support evtx log files without workaround

### ISSUE THREAD

**Issue by Techcadia** [fluent/fluent-plugin-windows-eventlog#15]
Currently only items listed under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog` are accessible to this plugin. This is due to the underlying [win32-eventlog](https://github.com/chef/win32-eventlog) gem only providing access to the listed logs.

Bellow are a list of them on Sever 2016
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\HardwareEvents
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Internet Explorer
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Key Management Service
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Security
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\System
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Windows PowerShell
```

WARNING: if the channel can't be found in this registry location by the underlying [Win32 call](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-openeventlogw) it just returns `Application`

I have been trying to monitor IIS logs at `Microsoft-IIS-Logging/Logs` but since they are in the new evtx format, they are not found by default.

There is a work around.

You can add the facade to access any evtx file via adding a registry key.
```
$LogName = 'Microsoft-IIS-Logging/Logs'
$LogPath = $(Get-WinEvent -ListLog $LogName).LogFilePath
$RegPath = "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\${LogName}"
REG ADD $RegPath /v 'File' /d $LogPath /t REG_EXPAND_SZ
```
NOTE: The reason we can't use New-Item is because the forward [slash gets escaped](https://www.reddit.com/r/PowerShell/comments/34kvyv/how_do_you_escape_in_powershell/cqvs30u/).

**Comment by tedkol** [comment]
I hit the same issue with a different eventlog  path. I haven't been successful in using the workaround (but thanks for the warning! I was baffled why the application logs starting showing up in the new channel.)

**Comment by repeatedly** [comment]
We are now considering new plugin with new windows eventlog API: https://github.com/fluent/fluent-plugin-windows-eventlog/pull/21
Does new windows eventlog API provide function to spcify service list?

**Comment by cosmo0920** [comment]
From https://github.com/fluent/fluent-plugin-windows-eventlog/issues/47, we can recommend to use `in_windows_eventlog2` to read evtx format channel.
Closing.
