### ISSUE TITLE
Use Windows Event Log API instead of Event Logging API

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluent-plugin-windows-eventlog#19]
Currently, this plugin uses Event Logging API and Event Logging API is for older Windows.

https://docs.microsoft.com/en-us/windows/desktop/eventlog/event-logging-reference

This API still works but Microsoft recommends to use Windows Event Log for recent Windows.

We need the advice from windows expert for these APIs.

**Comment by muffins** [comment]
Out of curiosity, is this issue considered closed/addressed? Looks like there was a considerable amount of work done in #21 related to this, was just curious what the expected status is?

**Comment by repeatedly** [comment]
I think this issue can be closed. cc: @cosmo0920

**Comment by cosmo0920** [comment]
Yep, we can close this! :muscle:
