### ISSUE TITLE
unable to install fluent-plugin-windows-eventlog 0.3.0

### ISSUE THREAD

**Issue by mseka1** [fluent/fluent-plugin-windows-eventlog#22]
I'm unable to install the newest version. the following is the error message i'm getting  
current directory: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/winevt_c-0.5.1/ext/winevt
C:/opt/td-agent/embedded/bin/ruby.exe -r ./siteconf20190713-6184-a4vsfm.rb extconf.rb
checking for -lwevtapi... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/opt/td-agent/embedded/bin/$(RUBY_BASE_NAME)
        --with-winevt-dir
        --without-winevt-dir
        --with-winevt-include
        --without-winevt-include=${winevt-dir}/include
        --with-winevt-lib
        --without-winevt-lib=${winevt-dir}/lib
        --with-wevtapilib
        --without-wevtapilib
C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:468:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:553:in `try_link0'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:568:in `try_link'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:787:in `try_func'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:1014:in `block in have_library'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:957:in `block in checking_for'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:956:in `checking_for'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:1009:in `have_library'
        from extconf.rb:13:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/winevt_c-0.5.1/mkmf.log

extconf failed, exit code 1

--------------------------------------------
Here is the content from   C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/winevt_c-0.5.1/mkmf.log

"gcc -o conftest.exe -IC:/opt/td-agent/embedded/include/ruby-2.4.0/x64-mingw32 -IC:/opt/td-agent/embedded/include/ruby-2.4.0/ruby/backward -IC:/opt/td-agent/embedded/include/ruby-2.4.0 -I. -IC:/opt/td-agent/embedded/include -DFD_SETSIZE=2048 -m64 -march=x86-64 -O2 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -IC:/opt/td-agent/embedded/include -DFD_SETSIZE=2048 -march=x86-64 -O2 -fno-omit-frame-pointer conftest.c  -L. -LC:/opt/td-agent/embedded/lib -LC:/opt/td-agent/embedded/lib -L. -LC:/opt/td-agent/embedded/lib -fno-lto  -m64   -lx64-msvcrt-ruby240  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

**Comment by mseka1** [comment]
Server typre Wndows 2016 
64 bit Operating system

**Comment by cosmo0920** [comment]
Could you provide installation command which you used.
winevt_c gem requests to build its C/C++ extension code with gcc and g++ which is originated from MSYS2.

**Comment by mseka1** [comment]
@cosmo Here is the commands i'm running 

1) C:\opt\td-agent\embedded\bin\fluent-gem install fluent-plugin-windows-eventlog -v 0.3.0 --no-ri --no-rdoc

OR 
2)we download from a site where we load all our binaries and use the following command
C:\opt\td-agent\embedded\bin\fluent-gem install fluent-plugin-windows-eventlog --source https://abc/fluent-plugin-windows-eventlog-0.3.0.gem --no-ri --no-rdoc

Do you know when the fix will be merged. I'm still having the issue

**Comment by Cosmo** [comment]
@mseka1 cool. but i'm another cosmo :)

**Comment by mseka1** [comment]
@cosmo0920  I have included the commands. Please check above

**Comment by cosmo0920** [comment]
Hmm..., it is little bit hard to install in td-agent installed and not installed MSYS2 system.
Could you try to install fluent-plugin-windows-eventlog with the [this fat gem](https://github.com/cosmo0920/winevt_c/releases/download/v0.5.1/winevt_c-0.5.1-x64-mingw32.gem)?
I'll consider about how to install winevt_c gem on Windows for absent of MSYS2 case.

**Comment by mseka1** [comment]
@cosmo0920  What name should i use under source section? Successfully installed your gem but it keeps getting unknown plugin . <source>
  
Error message:
2019-07-16 18:53:31 +0000 [trace]: fluent/log.rb:281:trace: registered buffer plugin 'file'
2019-07-16 18:53:31 +0000 [info]: fluent/log.rb:322:info: brokers has been set directly: ["psdpeitokfk01.cloud.capitalone.com:9093", "psdpeitokfk02.cloud.capitalone.com:9093"]
2019-07-16 18:53:31 +0000 [error]: fluent/log.rb:362:error: config error file="C:/opt/td-agent/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown input plugin 'winevt_c'. Run 'gem search -rd fluent-plugin' to find plugins"
  2019-07-16 18:53:31 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/registry.rb:48:in `lookup'
  2019-07-16 18:53:31 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin.rb:146:in `new_impl'
  2019-07-16 18:53:31 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin.rb:100:in `new_input'
  2019-07-16 18:53:31 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:315:in `add_source'
  2019-07-16 18:53:31 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:160:in `block in configure'
  2019-07-16 18:53:31 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:156:i

**Comment by igorpeshansky** [comment]
@mseka1, I think you want to put `@type windows_eventlog` (or `@type windows_eventlog2`) in your config. See [README.md](https://github.com/fluent/fluent-plugin-windows-eventlog/blob/master/README.md).

**Comment by mseka1** [comment]
@igorpeshansky I tried @type windows_eventlog2 but i got the same Unknown plugin error.

2019-07-16 23:56:48 +0000 [error]: fluent/log.rb:362:error: config error file="C:/opt/td-agent/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown input plugin 'windows_eventlog2'. Run 'gem search -rd fluent-plugin' to find plugins"
  2019-07-16 23:56:48 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/registry.rb:48:in `lookup'

**Comment by mseka1** [comment]
I appreciate all your help on this. I  was able to install and successfully start fluentd with the newest version

**Comment by cosmo0920** [comment]
Whoa, great job, @mseka1 !

**Comment by ksandrmatveyev** [comment]
Hi gents. @mseka1 / @cosmo0920 , could you share with cmd for install new version of windows_eventlog 0.3.0? I'm still facing with the same issue as @mseka1 had

**Comment by cosmo0920** [comment]
New version of windows eventlog requests to build with MSYS2.
MSYS2 is bundled in RubyInstaller with DevKit.
To invoke MSYS2 compilers, ridk exec gem install or ridk exec bundle install is needed.

**Comment by ksandrmatveyev** [comment]
Sorry for silly question @cosmo0920 / @mseka1 .
Well, I installed fluent-plugin-windows-eventlog 0.3.0 with
```
# RubyInstaller https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-2.5.5-1
C:\Ruby25-x64\bin\ridk exec gem install fluent-plugin-windows-eventlog
```
and can run td-agent with  `PS C:\Ruby25-x64\bin> .\fluentd -c C:\opt\td-agent\etc\td-agent\td-agent.conf` (that includes in_windows_eventlog2). 

Question is how I can add these gems (winevt_c and fluent-plugin-windows-eventlog 0.3.0) to td-agent that was installed via msi (3.4.1)? I can't install 

Is there any plan to build new msi package for td-agent?
