### ISSUE TITLE
Unable to send from all channels

### ISSUE THREAD

**Issue by mseka1** [fluent/fluent-plugin-windows-eventlog#24]
I'm trying to send the following logs using fluent-plugin-windows-eventlog 
Security, System, Directory Service, Active Directory Web Services, DFS Replication, Windows PowerShell, HardwareEvents

Only security and system are getting sent . All other channels don't

**Comment by mseka1** [comment]
here is my config:
<source>
  @type windows_eventlog2
  @id @type windows_eventlog2
  channels ["Security", "System", "Directory Service", "Active Directory Web Services", "DFS Replication", "Windows PowerShell", "HardwareEvents"]
    read_interval 10
  tag winevt.raw
  <storage>
   @type local
   persistent false
  </storage>
 <parse>
    @type none
 </parse>
</source>


<filter winevt.*>
 @type record_transformer
 enable_ruby
  <record>
  fluent_time ${Time.now.strftime('%Y-%m-%dT%H:%M:%S%z')}
  </record>
</filter>

<match winevt.*>
   @type stdout

</match>

**Comment by mseka1** [comment]
```<source>
  @type windows_eventlog2
  @id @type windows_eventlog2
  channels ["Security", "System", "Directory Service", "Active Directory Web Services", "DFS Replication", "Windows PowerShell", "HardwareEvents"]
    read_interval 10
  tag winevt.raw
  <storage>
   @type local
   persistent false
  </storage>
 <parse>
    @type none
 </parse>
</source>


<filter winevt.*>
 @type record_transformer
 enable_ruby
  <record>
  fluent_time ${Time.now.strftime('%Y-%m-%dT%H:%M:%S%z')}
  </record>
</filter>

<match winevt.*>
   @type stdout

</match> ```

**Comment by mseka1** [comment]
@cosmo0920  Any suggestion my friend. We have been struggling with this for 9 months

**Comment by cosmo0920** [comment]
Could you check events existence for target channels with event viewer?

I found that `"Directory Service", "Active Directory Web Services", "DFS Replication"` channels doesn't exist in my laptop.
Hardware events channel exists but is has no event.

And, these channel requests users whose has administrator privileges to read them.

**Comment by mseka1** [comment]
@cosmo0920 I installed the plugin on a window server no on a laptop. We have been struggling with getting all these channels . If anybody can help with this issue. We have been struggling since December 2018. If this plugin is just for laptop then i can explore other tools. We are running fluentd as admin.

**Comment by cosmo0920** [comment]
First, you should confirm to be able to get your target channels with windows builtin event viewer tool.
Your target channels can handle with builtin event viewer?
If they can be handled with event viewer, winevt_c is something wrong.

**Comment by cosmo0920** [comment]
Hi, @mseka1!
I've confirmed that this issue should be a bug for in_windows_eventlog2.
escaping character methods did escape for a space ` `.
The next release will be fixed this issue.
