### ISSUE TITLE
Library names injected if message not found in the message table

### ISSUE THREAD

**Issue by Project0** [fluent/fluent-plugin-windows-eventlog#35]
Note sure where is it coming from, but i see the library names only when the event log has no proper description.
I am using the eventlog2 plugin.

```json 
"DescriptionTitle": "The message resource is present but the message was not found in the message table.\r\n0.4.6/fluent/plugin/parser_winevt_xml.so"
```

```json 
"DescriptionTitle": "The message resource is present but the message was not found in the message table.\r\nib/fluent/plugin/in_windows_eventlog2.rb",
"EventData": [
  "C:\\ProgramData\\Datadog\\datadog.yaml seems to contain a valid configuration, not overwriting config"
],
```

**Comment by cosmo0920** [comment]
This is because message resource is not installed properly.
This phenomenon is also observed in Windows' event log viewer.
This is plugin limitation.

see: 
> NOTE: When Description contains error message such as The message resource is present but the message was not found in the message table., eventlog's resource file (.mui) related to error generating event is something wrong. This issue is also occurred in built-in Windows Event Viewer which is the part of Windows management tool.

**Comment by Project0** [comment]
sorry, but i am not alking about the message itself, its regarding the injected libary name in the message: `r\n0.4.6/fluent/plugin/parser_winevt_xml.so`.

**Comment by cosmo0920** [comment]
Strictly speaking, we just use [EvtFormatMessage](https://docs.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtformatmessage) to obtain events's Description.
This library name log glitch is caused by this Windows API....
We cannot fix it.
