### ISSUE TITLE
read_from_head activates if you close fluentd too soon

### ISSUE THREAD

**Issue by flurreN** [fluent/fluent-plugin-windows-eventlog#40]
I added 100+ eventlog channels but some of them have very low activity, so when fluentd starts, it wont add a RecordID in the storage file to the channels that havent logged anything yet.
When restarting fluentd, it will _read from the head_ on the channels that does not have a RecordID in the storage file. Is there anyway to fix this?

Config:
```
<source>
	@type			windows_eventlog2
	@id			windows_eventlog2
	channels		["..."]
	render_as_xml		true
	rate_limit		250
	parse_description	true
	read_from_head	     	false
	
	<storage>
		@type		local
		persistent	true
		path		c:/opt/tmp/storage.json
	</storage>	
	<parse>
		@type		winevt_xml
	</parse>
</source>	

```

**Comment by flurreN** [comment]
After some more digging I found that some of the channels in the storage file looks like this

`  "hardwareevents": "<BookmarkList Direction='backward'>\r\n</BookmarkList>",`
So for some reason some channels gets Direction='backward'

**Comment by cosmo0920** [comment]
Thanks for the detailed report.
I also got Direction='backward' result when subscribing empty channel.
I'm considering how to fix or find workaround.

**Comment by cosmo0920** [comment]
I'm developing this issue's workaround.
With #42 patch, we can subscribe channels like as:

```aconf
<subscribe>
  channels ["TargetChannel"]
  read_existing_events true
</subscribe>
<subscribe>
  channels ["TargetChannel"]
  read_existing_events false
</subscribe>
```

This will be handled as the following when without bookmark:

* The prior case is subscribing TargetChannel with EvtSubscribeToFutureEvents
* The latter case is subscribing TargetChannel with EvtSubscribeStartAtOldestRecord

ref: https://docs.microsoft.com/en-us/windows/win32/api/winevt/ne-winevt-evt_subscribe_flags

But I have no idea why the empty channel is not consumed until Fluentd restart....

**Comment by flurreN** [comment]
Not sure if read_existing_events was suppose to fix it but after some test runs I got this.

```
channels Security,Application
read_existing_events false
Run 1: {"application":"<BookmarkList Direction='backward'>\r\n</BookmarkList>","security":"<BookmarkList>\r\n  <Bookmark Channel='Security' RecordId='23460' IsCurrent='true'/>\r\n</BookmarkList>"}
Run 2: {"application":"<BookmarkList>\r\n  <Bookmark Channel='Application' RecordId='931' IsCurrent='true'/>\r\n</BookmarkList>","security":"<BookmarkList>\r\n  <Bookmark Channel='Security' RecordId='23460' IsCurrent='true'/>\r\n</BookmarkList>"}
```


```
channels Security,Application
read_existing_events false
Run 1: {"application":"<BookmarkList>\r\n</BookmarkList>","security":"<BookmarkList>\r\n  <Bookmark Channel='Security' RecordId='23464' IsCurrent='true'/>\r\n</BookmarkList>"}
Run 2: {"application":"<BookmarkList>\r\n  <Bookmark Channel='Application' RecordId='600' IsCurrent='true'/>\r\n</BookmarkList>","security":"<BookmarkList>\r\n  <Bookmark Channel='Security' RecordId='23464' IsCurrent='true'/>\r\n</BookmarkList>"}
```

```
channels application
read_existing_events false
Run 1: {"application":"<BookmarkList Direction='backward'>\r\n</BookmarkList>"}
Run 2: {"application":"<BookmarkList>\r\n  <Bookmark Channel='Application' RecordId='201' IsCurrent='true'/>\r\n</BookmarkList>"}
```

Same results with:
```
<subscribe>
  channels ["Application"]
  read_existing_events false
</subscribe>
```

Isnt it possible to make something like `<BookmarkList Direction='forward'>`? and force it to wait until a new log comes is, because if not closing fluentd to soon and for example a log comes into "Application" then it will continue from that point.

**Comment by cosmo0920** [comment]
> Isnt it possible to make something like <BookmarkList Direction='forward'>? 

No. This behavior is from Windows API which is provided by winevt.h. We cannot customize them.

**Comment by flurreN** [comment]
@cosmo0920 
From https://github.com/fluent-plugins-nursery/winevt_c/blob/2e9eec20107d242a2cab8d8678652d9d02c12e79/ext/winevt/winevt_subscribe.c
```
  if (hBookmark) {
    flags |= EvtSubscribeStartAfterBookmark;
  } else if (winevtSubscribe->readExistingEvents) {
    flags |= EvtSubscribeStartAtOldestRecord;
  } else {
    flags |= EvtSubscribeToFutureEvents;
  }
```

Im having trouble building the gem by myself so I cant really test it, but do you think 
```
  } else if (winevtSubscribe->readExistingEvents) {
    flags |= EvtSubscribeStartAtOldestRecord;
```
is being triggered when its suppose to use `EvtSubscribeToFutureEvents` ?


Sometimes it writes out `Direction="backward"`, but sometimes it doesnt not, when its not the wrong if statement is being triggered.

```
PS C:\Users\x\Desktop\winevt_c> gc C:\opt\tmp\storage0220-4.json -wait
{"application":"<BookmarkList>\r\n</BookmarkList>"}
PS C:\Users\x\Desktop\winevt_c> ^C
PS C:\Users\x\Desktop\winevt_c> gc C:\opt\tmp\storage0220-4.json -wait
{"application":"<BookmarkList Direction='backward'>\r\n</BookmarkList>"}

```

**Comment by flurreN** [comment]
Looks like because fluentd always write out `{"application":"<BookmarkList'>\r\n</BookmarkList>"}` it will always trigger the first if statement in this code on the second fluentd run, because the bookmark already exist on the 2nd run. 
Because it says `EvtSubscribeStartAfterBookmark ` and the bookmark is incomplete , it will start from the begining. Looks like thats the way  `EvtSubscribeStartAfterBookmark ` is working.
```
  if (hBookmark) {
    flags |= EvtSubscribeStartAfterBookmark;
  } else if (winevtSubscribe->readExistingEvents) {
    flags |= EvtSubscribeStartAtOldestRecord;
  } else {
    flags |= EvtSubscribeToFutureEvents;
  }
```

So to fix this is it possible to rewrite this and check if the bookmark actually is complete?

**Comment by cosmo0920** [comment]
> So to fix this is it possible to rewrite this and check if the bookmark actually is complete?

In winevt_c extension side, it is not possible.
But in Ruby side with nokogiri, we can check incomplete bookmark with XML parsing.



> Because it says `EvtSubscribeStartAfterBookmark ` and the bookmark is incomplete , it will start from the begining. Looks like thats the way `EvtSubscribeStartAfterBookmark ` is working.

Yep. You are right. I'm thinking of how to handle incomplete bookmark mechanism.

**Comment by cosmo0920** [comment]
> Isnt it possible to make something like `<BookmarkList Direction='forward'>`?

Without Direction means Direction='forward'.

```ruby
require 'winevt'

bookmark_str = <<EOS
<BookmarkList Direction='forward'>
</BookmarkList>
EOS

bookmark = Winevt::EventLog::Bookmark.new(bookmark_str)
bookmark.render #=> "<BookmarkList>\r\n</BookmarkList>"
```

**Comment by cosmo0920** [comment]
I'd created the patch to validate bookmark contents.
Could you try it out, @flurreN ?

**Comment by flurreN** [comment]
> I'd created the patch to validate bookmark contents.
> Could you try it out, @flurreN ?

Works for me!
