### ISSUE TITLE
Logs are not coming for Windows security channel with in_windows_eventlog (old plugin)

### ISSUE THREAD

**Issue by yeruvass** [fluent/fluent-plugin-windows-eventlog#44]
Hi Team,

I'm trying to read all channels using td-agent in windows environment. I can see all application,system and windows powershell logs but security channel information is not getting. I'm running fluentd as admin privileges. No issues in logs also .
I can see security event file storage is 2GB. Is any issues with large file?

environment :windows
software :- td-agent-3.3.0-1-x64.msi

**Comment by cosmo0920** [comment]
Could you share your configuration without sensitive information?
And this issue should be handled in Windows EventLog plugin.

**Comment by yeruvass** [comment]
@cosmo0920 , Thnaks for quick response. PFA configuration file.

**Comment by cosmo0920** [comment]
We'd founded that in_windows_eventlog(windows_eventlog in source) is not working correctly.
Instead, we recommend to use windows_eventlog2.
Could you upgrade your using td-agent3 for windows?

**Comment by yeruvass** [comment]
I'll try with windows_eventlog2.

**Comment by yeruvass** [comment]
@cosmo0920 , I have used  windows_eventlog2. I can fetch all security channels. Thanks for your suggestions.

**Comment by cosmo0920** [comment]
Wow. I'm glad to hear that! :muscle:

**Comment by cosmo0920** [comment]
win32-eventlog cannot handle security events which contains UserData case.
win32-eventlog is not maintained by us but winevt_c is developed and maintained by us.
We recommend to use in_windows_eventlog2 for such fetching Security channel case and won't fix in_windows_eventlog buggy behavior.

Anyway, thanks for your report and testing!

**Comment by repeatedly** [comment]
@cosmo0920 How about showing warning message when users use `in_windows_eventlog`?

**Comment by cosmo0920** [comment]
Oh, sounds good.
I'll give it a try.

**Comment by ameyah** [comment]
> We recommend to use in_windows_eventlog2 for such fetching Security channel case

@cosmo0920 I am using the windows_eventlog2 to fetch events with UserData but still the UserData values don't seem to appear. Other fields do appear, but I am interested in the UserData fields. Is this not supported?
