### ISSUE TITLE
Feature Request: Set log language/locale

### ISSUE THREAD

**Issue by gschanuel** [fluent/fluent-plugin-windows-eventlog#46]
I'm using in_windows_eventlog2  to forward logs from ActiveDirectory to a centralized server.
I also set parse_description to true.
My windows language is set to pt-br but I would like to get the description in English instead of the default language form the OS. 
Is that possible somehow?

**Comment by cosmo0920** [comment]
Currently, we didn't find to render arbitrary locale.
If you want to obtain EventLog as English, please set up System locale and account locale as English.

**Comment by cosmo0920** [comment]
This should be fixed in v0.7.0.

Since v0.7.0 and using winevt_c v0.8.1, adding `description_locale en_US` and English (United States) language pack should support to retrieve English EventLog description.
