### ISSUE TITLE
Feature Request: Subscribe to all log channels

### ISSUE THREAD

**Issue by flurreN** [fluent/fluent-plugin-windows-eventlog#47]
Wouldnt it be possible to get all the channels with this [function](https://docs.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtopenchannelenum)
"Gets a handle that you use to enumerate the list of channels that are registered on the computer."

Currently im using a powershell script to get all the channels but would be easier if it was built into the plugin.

**Comment by cosmo0920** [comment]
Hmm.., we can implement this feature request with https://rdoc.info/gems/winevt_c/0.7.0/Winevt%2FEventLog%2FChannel:each.

**Comment by flurreN** [comment]
> Hmm.., we can implement this feature request with https://rdoc.info/gems/winevt_c/0.7.0/Winevt%2FEventLog%2FChannel:each.
Oh did not know that one worked like that. Seemse to be really easy to implement this. If you are not already on it I can try to get it done tomorrow.

**Comment by flurreN** [comment]
Do you know if there is a max amount of channel it can subscribe to? Feels like this picks up way to many channels which gives me error 50:

`2020-02-26 10:57:54 +0100 [error]: #0 config error file="etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Invalid Bookmark XML is loaded. ErrorCode: 50\nError: Beg\u00E4ran st\u00F6ds inte.\r\n\n"`

**Comment by cosmo0920** [comment]
> Do you know if there is a max amount of channel it can subscribe to? Feels like this picks up way to many channels which gives me error 50:
> 
> `2020-02-26 10:57:54 +0100 [error]: #0 config error file="etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Invalid Bookmark XML is loaded. ErrorCode: 50\nError: Beg\u00E4ran st\u00F6ds inte.\r\n\n"`

This should be Debug or Analytical EventLog channel case, I guess:
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs#L627-L633

This skipping feature for Debug or Analytical cases is not implemented in winevt_c.
We should implement it first instead of just using [Pokemon exception handling](https://wiki.c2.com/?PokemonExceptionHandling).

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluent-plugin-windows-eventlog/pull/48 is merged. Closing.
