### ISSUE TITLE
Original security message is removing when parse_description is true

### ISSUE THREAD

**Issue by yeruvass** [fluent/fluent-plugin-windows-eventlog#49]
@cosmo0920 ,
As per fluentd document, Description and EventData fields are removed when we set **parse_description true.**  How to add Description field when we set parse_description true
https://github.com/fluent/fluent-plugin-windows-eventlog

Example config :-
```aconf
<source>
  @type windows_eventlog2
  @id windows_eventlog2
  channels Application,System,Security,Windows PowerShell
  tag enbd-windows-secuirty-events
  render_as_xml false
  #parse_description true
  <storage>
    @type local
    persistent true
    path C:/opt/td-agent/etc/td-agent/pos/windowsecuritysevent.pos
  </storage>
</source>
```

**Comment by cosmo0920** [comment]
No way to reserve them. Thanks.

**Comment by cosmo0920** [comment]
I won't to introduce implementation complexity to preserve original fields.
This should be won't fix.
Closing.
