### ISSUE TITLE
fluentd_windows_customisedapplication logs

### ISSUE THREAD

**Issue by muralikri32** [fluent/fluent-plugin-windows-eventlog#51]
Hi,
I have configured Fluentd on windows server (WIN 2012) and trying to tail customized application logs (which is present in C:/opt/td-agent/application.log) to elastic search. Each time when i configure and start the agent i could see that "fluentd worker is now running worker=0" message in Kibana but not my application logs. config details given below, please help to fix the issue.

config:
```aconf
##INPUT 
<source>
  @type tail
  @id input_tail
  format single_value
  <parse>
  type none
  </parse>
  path /opt/td-agent/application.log
  pos_file /opt/td-agent/applog.pos
  tag server.app.log
</source>

##output config path
<match *.**>
  @type forward
  @type elasticsearch
  host elastic-search-hostname
  port 9200
  logstash_format false
  include_timestamp true
  index_name fluentd_server
</match>
```

**Comment by flurreN** [comment]
Do you know if fluentd reads from the .log file correctly? I would say try with [stdout](https://docs.fluentd.org/output/stdout) and run fluentd from td-agent command promt so you can see if it does.

**Comment by muralikri32** [comment]
Hi,

Yes, i tried with stdout and it reads from .log and even tried with .txt. I am able to index the same type of logs from Linux machine. But not sure why it is not read or index from.windows machine

**Comment by cosmo0920** [comment]
> I have configured Fluentd on windows server (WIN 2012) and trying to tail customized application logs (which is present in C:/opt/td-agent/application.log) to elastic search. Each time when i configure and start the agent i could see that "fluentd worker is now running worker=0" message in Kibana but not my application logs. config details given below, please help to fix the issue.

This should be generated from Fluentd itself.

The below configuration should omit  "fluentd worker is now running worker=0" from source events.

```aconf
# omit other source / match
# and put it before match.
<label @FLUENT_LOG>
  <match fluent.*>
    @type null
  </match>
</label>
```

ref: https://docs.fluentd.org/deployment/logging#capture-fluentd-logs

But this issue ticket is used for fluent-plugin-windows-eventlog not for other core plugin question.
Closing.
