### ISSUE TITLE
How does it keep track of forwarded events to the same channel

### ISSUE THREAD

**Issue by philipsabri** [fluent/fluent-plugin-windows-eventlog#61]
We are trying to see if forwarding events and then collecting them with fluentd is a better choice for us.

But how does it keep track of the forwarded events? When lookin in the storage file it look like this
`{"wec-authentication":"<BookmarkList>\r\n  <Bookmark Channel='WEC-Authentication' RecordId='3954582302' IsCurrent='true'/>\r\n</BookmarkList>"}`

The `RecordId='3954582302'`, but how does it keep track when different servers send different RecordId's from different channels

Example:
Server A sends `EventRecordID 11920` from `Security ` to the forwarded collecting channel X
Server B sends `EventRecordID 219130` from `Security ` to the forwarded collecting channel X
Server B sends `EventRecordID 11910` from `Application` to the forwarded collecting channel X

FluentD collects everything from Channel X, how does it keep track of that?

![image](https://user-images.githubusercontent.com/4808216/85395585-acd6f080-b550-11ea-98ff-9ea22ef633dd.png)
EventRecordID and Channel from different servers but collected from the same forwarded channel

**Comment by samsplunks** [comment]
Also interested about the behaviour regarding Forwarded Events as it is a common case in a WEC architecture.

**Comment by samsplunks** [comment]
Well, it does keep track of the events in the wrong way and creates inconsistent log forwarding.

I have a Windows Event Collector server receiving logs from different clients on a specific channel.

Client A sends a log at 12:18 with those two fields:
```
  <TimeCreated SystemTime="2021-XX-XXT12:08:04.199751100Z" /> 
  <EventRecordID>91630237</EventRecordID>
```

Client B sends a log at 12:58 on the same day:
```
  <TimeCreated SystemTime="2021-XX-XXT12:58:02.820966700Z" /> 
  <EventRecordID>46469305</EventRecordID> 
```

FluentD has recorded the position of the 12:08 event with:
`{"CustomChannel":"<BookmarkList>\r\n  <Bookmark Channel='CustomChannel' RecordId='91630237' IsCurrent='true'/>\r\n</BookmarkList>"}`

All the logs coming in after 12:08 that have an EventRecordID lower than 91630237 will be dismissed.

The bookmark needs to account for a field belonging to the server receiving the logs, the only one I see is TimeCreated SystemTime.

Would it be possible to control a "bookmark_field" parameter in the plugin?

Please, tag this issue as a bug.

**Comment by samsplunks** [comment]
When fluentd queries the ForwardedEvents channel, it receives eventlogs with **EventRecordID**s.

What the bookmark saves is the internal **RecordId** (without Event) of the channel that is queried through the EventLog API.

Open **irb** shell from FluentD bin folder and try it for yourself:

```
require 'winevt'

@query = Winevt::EventLog::Query.new("WEC-Authentication", "*[System[(EventID=4624)]]")

@bookmark = Winevt::EventLog::Bookmark.new

@query.each do |xml|
  @bookmark.update(@query)
  puts xml
  puts @bookmark.render
end
```
