### ISSUE TITLE
Missing UserData section from Applocker logs.

### ISSUE THREAD

**Issue by recabarren** [fluent/fluent-plugin-windows-eventlog#63]
Hi, I have configured the windows_eventlog2 plugin in order to obtain applocker logs from my windows machines. 

Specifically, I have configured fluentd 3.5.1.0 stable to get the microsoft-windows-applocker/exe and dll channel, and everything works as expected for the System section of the log, i.e. I am able to see attributes like: provider, eventId, etc. However, I can not see any of the UserData section attributes, for instance, FileHash or FileHashLength. Am I doing something wrong or is this a missing feature / known limitation?

Thanks a lot!

**Comment by cosmo0920** [comment]
> However, I can not see any of the UserData section attributes, for instance, FileHash or FileHashLength. Am I doing something wrong or is this a missing feature / known limitation?

Yeah, UserData section attributes drop on `render_as_xml` as `false`. To obtain attributes, you should use `render_as_xml` as `true` and parse XML by your custom XML formatted parser plugin.

**Comment by recabarren** [comment]
Thanks a lot! Yep, this fixed the issue. Thanks!!
