### ISSUE TITLE
Incorrect / misleading documentation for in_windows_eventlog2 channels parameter

### ISSUE THREAD

**Issue by randomchance** [fluent/fluent-plugin-windows-eventlog#68]
The **in_windows_eventlog2** [documentation](https://github.com/fluent/fluent-plugin-windows-eventlog#parameters-1) says that there are only 4 valid logs / channels, however that is not true.

> One or more of {'application', 'system', 'setup', 'security'}.

This implies that these are the only options, and that channels such as `Microsoft-Windows-DiskDiagnostic/Operational` are not supported.

I actually rejected fluentd as a logging solution based on the above documentation after a only brief test, and have been stuck fighting logstash config syntax. 

However, @fifofonix [showed me](https://github.com/grafana/loki/issues/1395#issuecomment-717950670) that all the windows log channels are supported. 

```
<source>
  @type windows_eventlog2
  @id windows_eventlog2
  # Do not quote "" or escape \ characters in channel names...
  channels application,system,security,HardwareEvents,Windows PowerShell, Microsoft-Windows-Diagnosis-PCW/Operational 
</source>
```

It's too late for me, but if you hurry you can save countless others!

**Comment by cosmo0920** [comment]
> The **in_windows_eventlog2** [documentation](https://github.com/fluent/fluent-plugin-windows-eventlog#parameters-1) says that there are only 4 valid logs / channels, however that is not true.
> 
> > One or more of {'application', 'system', 'setup', 'security'}.
> 
> This implies that these are the only options, and that channels such as `Microsoft-Windows-DiskDiagnostic/Operational` are not supported.

Oh, no! :scream:
This documentation is outdated. Sorry for outdated documentation.
Yeah, `in_windows_eventlog2` could handle all of channels of Windows EventLog.
This line was just copy and pasted from `in_windows_eventlog`, which is the old one, documentation....

**Comment by cosmo0920** [comment]
I'd sent a PR to fix this outdated documentation issue.

PR #69 is enough for you, @randomchance ?

**Comment by randomchance** [comment]
@cosmo0920  That's perfect, thank you.
