### ISSUE TITLE
render_as_xml does not work?

### ISSUE THREAD

**Issue by coffee5280** [fluent/fluent-plugin-windows-eventlog#84]
Hello FluentD team,

I am attempting to use FluentD to collect Windows event logs using the following configuration:
```
<source>
  @type windows_eventlog2
  @id windows_eventlog2
  channels application
  read_existing_events true
  tag winevt.raw
  render_as_xml true
  rate_limit 200
  <storage>
    @type local
    persistent true
    path C:\opt\td-agent\winlog.json
  </storage>
</source>

<match winevt.raw>
  @type stdout
</match>
```

The logs are printing to STDOUT as expected, however they are in JSON format.  The only change I am seeing between using 'render_as_xml true' and 'render_as_xml false' is that the EventIDs are properly displayed with the value set to 'true'.  Otherwise there is no change of the actual format of the log being printed to STDOUT.  I have also tried adding a <parse> section to the config, with no effect.

**What I am expecting to see is a log that looks something like this (Actual XML log from my system - fields changed to scrub my PID):**
```
<Event xmlns=“http://schemas.microsoft.com/win/2004/08/events/event”>
 <System>
  <Provider Name=“Microsoft-Windows-Security-SPP” Guid=“{00000000-C8C9-472C-A5F9-000000000000}” EventSourceName=“Software Protection Platform Service” />
  <EventID Qualifiers=“16384”>16384</EventID>
  <Version>0</Version>
  <Level>4</Level>
  <Task>0</Task>
  <Opcode>0</Opcode>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime=“2022-01-14T20:32:39.2460562Z” />
  <EventRecordID>24551</EventRecordID>
  <Correlation />
  <Execution ProcessID=“0” ThreadID=“0" />
  <Channel>Application</Channel>
  <Computer>DESKTOP-00000</Computer>
  <Security />
 </System>
 <EventData>
  <Data>2121-12-21T20:32:39Z</Data>
  <Data>RulesEngine</Data>
 </EventData>
</Event>
```

**and NOT like this:**
```
2022-01-14 14:20:31.395438200 -0700 winevt.raw: {“ProviderName”:“Microsoft-Windows-Security-SPP”,“ProviderGUID”:“”,“EventID”:“16384",“Level”:“4",“Task”:“0",“Opcode”:“0",“Keywords”:“0x80000000000000",“TimeCreated”:“2022/01/14 20:32:39.246056200",“EventRecordID”:“24551",“ActivityID”:“”,“RelatedActivityID”:“”,“ProcessID”:“0",“ThreadID”:“0",“Channel”:“Application”,“Computer”:“DESKTOP-00000”,“UserID”:“”,“Version”:“0",“Description”:“Successfully scheduled Software Protection service for re-start at 2121-12-21T20:32:39Z. Reason: RulesEngine.“,”EventData”:[“2121-12-21T20:32:39Z”,“RulesEngine”]}
```

**My question is this:  Is this feature bugged?  Or is it possibly just mis-named?**

Thank you.

**Comment by cosmo0920** [comment]
This is because the default parser type is culprit for your problem.
Try:

```aconf
<source>
  @type windows_eventlog2
  @id windows_eventlog2
  channels application
  read_existing_events true
  tag winevt.raw
  render_as_xml true
  rate_limit 200
  <storage>
    @type local
    persistent true
    path C:\opt\td-agent\winlog.json
  </storage>
  <parse>
    @type none # Specifying none parser is needed.
  </parse>
</source>

<match winevt.raw>
  @type stdout
</match>
```

**Comment by coffee5280** [comment]
> This is because the default parser type is the culprit for your problem. Try:
> 
> ```apache-config
> <source>
>   @type windows_eventlog2
>   @id windows_eventlog2
>   channels application
>   read_existing_events true
>   tag winevt.raw
>   render_as_xml true
>   rate_limit 200
>   <storage>
>     @type local
>     persistent true
>     path C:\opt\td-agent\winlog.json
>   </storage>
>   <parse>
>     @type none # Specifying none parser is needed.
>   </parse>
> </source>
> 
> <match winevt.raw>
>   @type stdout
> </match>
> ```

Thank you so much!  This is now working as expected.  I will close this comment out once I verify the results with my team.

**Comment by cosmo0920** [comment]
:tada:
