### ISSUE TITLE
EventId from Windows Eventlog is not the same in windows_eventlog2 plugin

### ISSUE THREAD

**Issue by kashok7474** [fluent/fluent-plugin-windows-eventlog#86]
### Describe the bug

Hi team, 
We have a fluentd based logging agent. we use the windows_eventlog2 plugin for streaming window event logs.
Recently we have noticed a specific event name(): Service control manager which has event id 7306 in the window system.
When fluend agent reading this event via windows_eventlog2 input plugin, event id w.r.t this event Service control manager is 1073748860.

We have observed this issue only with this specific event.  kindly let us know why this mismatch happening.
![Screenshot 2022-08-17 at 4 46 43 PM](https://user-images.githubusercontent.com/11617150/185108174-0376ab38-79d8-4efa-b2e5-d75c25b5a551.png)
<img width="847" alt="Capture2" src="https://user-images.githubusercontent.com/11617150/185108242-9c911108-20ae-4ba6-bd90-f56daea98fff.png">

### To Reproduce

1. Install fluend based agent on window machine.
2. used fluend.conf similar to below
3. used the following configuration:
```aconf 
  <source>
        @type windows_eventlog2
        tag test
        channels  Security, System, Application
        from_encoding  UTF-8
        encoding  UTF-8
        <storage>
            @type local
            persistent true
            path C:\testt\test\winevt.pos
        </storage>
    </source>

    <match 6a7371.**>
        @type stdout
    </match>
```

### Expected behavior

windows_eventlog2 plugin should read event id as 7306 not 1073748860

### Your Environment

```markdown
- Fluentd version: latest version
- TD Agent version:
- Operating system: Window
- Kernel version:
```

### Your Configuration

```apache
<source>
        @type windows_eventlog2
        tag test
        channels  Security, System, Application
        from_encoding  UTF-8
        encoding  UTF-8
        <storage>
            @type local
            persistent true
            path C:\testt\test\winevt.pos
        </storage>
    </source>

    <match 6a7371.**>
        @type stdout
    </match>`
```

### Your Error Log

```shell
Attached screen where we can clearly see event id 1073748860
```

### Additional context

Similar had been reported here https://github.com/graylog-labs/collector/issues/50

**Comment by cosmo0920** [comment]
> We have observed this issue only with this specific event. kindly let us know why this mismatch happening.

This is expected behavior.
This is caused by `Qualifiers` not to be zero case.
If the qualifiers are not zero, we calculated the following equation to show the correct Event ID:

`Shown EventID = (EventID & 0xffff) | (Qualifiers & 0xffff) << 16`

Ref: https://github.com/fluent-plugins-nursery/winevt_c/blob/9bcea0104249dee3c22a609d4a9e84f9d203cb36/ext/winevt/winevt_utils.cpp#L676

If you want to preserve qualifiers and non-qualified EventID, you have to specify `preserve_qualifiers_on_hash` as `true`. (default is false.)

**Comment by cosmo0920** [comment]
> Attached screen where we can clearly see event id 1073748860

```irb
$ irb
irb(main):001:0> 1073748860 & 0xffff
=> 7036
```

Then, this **is** expected behavior. Please adjust your windows_eventlog2 plugin's configuration. Thank you for using this plugin. :smile:
